version: '3.8'

services:
  dotnetapp:
    image: mcr.microsoft.com/dotnet/aspnet:8.0
    container_name: dotnetapp
    ports:
      - "8023:8023"  
    volumes:
      - ./dotnetapp:/app  
    working_dir: /app
    entrypoint: ["dotnet", "YourApp.dll"]
    depends_on:
      - db


  vue-app:
    container_name: vue-app
    build:
      context: ./CEMS-Server
      dockerfile: DockerFile
    ports:
      - "8024:8024"  
    environment:
      - TZ=Asia/Bangkok
    volumes:  
      - ./CEMS-Server:/usr/src/app 
      - /usr/src/app/node_modules
    stdin_open: true
    tty: true
    command: ["npm", "run", "dev"]


volumes:
  db_data: