FROM node:18-alpine

WORKDIR /usr/src/app

RUN apk add --no-cache tzdata

ENV TZ Asia/Bangkok

COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the port Vite is running on
EXPOSE 8024

# Run Vite in development mode
CMD ["npx", "vite", "dev"]

